import type { NextPage } from 'next'
import Head from 'next/head'
import AboutModule from '@modules/about/index';

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutModule template="poc" />
    </div>
  )
}

export default About
