import { GetStaticPropsContext, GetStaticPropsResult } from 'next';
import type { NextPage } from 'next'
import Head from 'next/head'
import AboutModule from '@modules/about/index';
import getAboutPageData from '@services/dato/getAboutPageData';

export async function getStaticProps({
  preview = false,
}: GetStaticPropsContext): Promise<GetStaticPropsResult<any>> {
  const aboutPageData: any = await getAboutPageData({ preview });

  return {
    props: {
      preview: preview || null,
      content: aboutPageData.data.about
    },
    revalidate: 900,
  };
}

type AboutProps = {
  content?: any;
}

const About:NextPage<AboutProps> = ({content}) => {
  
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutModule data={content}  />
    </div>
  )
}

export default About
